version: '3'
services:
    database:
        build: ./database
        ports:
            - "127.0.0.1:5432:5432"
    service:
        build: ./service
        ports:
            - "127.0.0.1:3000:3000"
        environment:
            PG_URI: postgres://postgres:postgres@database:5432/postgres
