version: 2
jobs:
  build_database:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Build Database Docker Image"
          working_directory: ~/repo/database
          command: |
            ./build.sh

  build_service:
    docker:
      # specify the version you desire here
      - image: circleci/golang:1.11

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: "Restore Service Cache"
          keys:
          - service-dependencies-{{ checksum "goservice/go.mod" }}
          # fallback to using the latest cache if no exact match is found
          - service-dependencies-
      - run:
          name: "Get Dependencies"
          command: |
              go get github.com/jstemmer/go-junit-report
              go get golang.org/x/lint/golint
      - run:
          name: "Build and Test Service"
          working_directory: ~/repo/goservice
          command: |
              export GO111MODULE=on
              go mod tidy
              golint ./...
              mkdir -p /tmp/test-results
              go test -v ./... 2>&1 | tee /tmp/test-results/output
              cat /tmp/test-results/output | go-junit-report > /tmp/test-results/go-test.xml

      - store_test_results:
          path: /tmp/test-results

      - save_cache:
          name: "Save Service Cache"
          paths:
            - "/go/pkg"
          key: service-dependencies-{{ checksum "goservice/go.mod" }}

  full_stack_test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "Full Stack Tests"
          working_directory: ~/repo
          command: |
              docker-compose -p worldstest -f docker-compose.test.yml up --build --exit-code-from=testing
      - store_test_results:
          path: ~/repo/build/reports

workflows:
  version: 2
  full_build:
      jobs:
          - build_database
          - build_service
          - full_stack_test:
              requires:
                  - build_database
                  - build_service
