version: 2
jobs:
  build_database:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Build Database Docker Image"
          working_directory: ~/repo/database
          command: |
            ./build.sh

  build_service:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: "Restore Service Cache"
          keys:
          - service-dependencies-{{ checksum "service/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - service-dependencies-
      - run:
          name: "Build and Test Service"
          working_directory: ~/repo/service
          command: |
              yarn install
              yarn lint
              yarn test
              yarn stryker --maxConcurrentTestRunners 3
      - store_test_results:
          path: ~/repo/service/build/test/reports
      - store_artifacts:
          path: ~/repo/service/build/reports/mutation/html
          destination: stryker-service
      - save_cache:
          name: "Save Service Cache"
          paths:
            - ~/service/node_modules
          key: service-dependencies-{{ checksum "service/package.json" }}

  full_stack_test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "Full Stack Tests"
          working_directory: ~/repo
          command: |
              docker-compose -p worldstest -f docker-compose.test.yml up --build --exit-code-from=testing
      - store_test_results:
          path: ~/repo/build/reports

workflows:
  version: 2
  full_build:
      jobs:
          - build_database
          - build_service
          - full_stack_test:
              requires:
                  - build_database
                  - build_service
