version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run: 
          name: "Build Database"
          working_directory: ~/repo/database
          command: |
            ./build.sh

      - restore_cache:
          name: "Restore Service Cache"
          keys:
          - service-dependencies-{{ checksum "service/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - service-dependencies-
      - run: 
          name: "Build and Test Service"
          working_directory: ~/repo/service
          command: |
              yarn install
              yarn test
      - store_test_results:
          path: ~/repo/service/build/test/reports
      - save_cache:
          name: "Save Service Cache"
          paths: 
            - ~/service/node_modules
          key: service-dependencies-{{ checksum "service/package.json" }}

